version: '4'

services:
  config:
    image: config
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - coffee

  discovery:
    image: discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - coffee

  gateway:
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - coffee

networks:
  coffee:
    driver: bridge
